# -*- coding: utf-8 -*-
"""CSS Essay Evaluator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SCW_AVfyfEfwUcUXfonyjP-fz2qYZoZF
"""

!pip install -U langchain_groq

from langgraph.graph import StateGraph, START, END
from typing import TypedDict
from langchain_groq.chat_models import ChatGroq

llm = ChatGroq(
    model="openai/gpt-oss-20b",
    temperature=0,
    api_key="api"
)

from typing import TypedDict

class ExamState(TypedDict):
  title: str
  content: str
  cot: float
  doa: float
  language: float

from langgraph.types import interrupt, Command

def generate_title_node(state: ExamState):

    response = llm.invoke(
        "Give me one essay title for CSS exam preparation. "
        "Return only the essay title."
    )

    title = response.content

    return {
        "title": title
    }

def ask_essay_node(state: ExamState):

    title = state["title"]

    user_essay = interrupt({
        "title": title,
        "message": "Write your complete essay on this topic."
    })

    return {
        "content": user_essay
    }

def cot_node(state: ExamState):

    content_to_analyze = state.get("content", "")

    prompt = f"""
    Analyze this essay:

    {content_to_analyze}

    Rate its critical thinking and originality (COT) out of 5.

    Return ONLY the number.
    """

    response = llm.invoke(prompt)

    try:
        score = float(response.content)
    except ValueError:
        score = 0.0

    return {"cot": score}

def doa_node(state: ExamState):

    content_to_analyze = state.get("content", "")

    prompt = f"""
    Analyze this essay:

    {content_to_analyze}

    Rate its DOA out of 5.

    Return ONLY the number.
    """

    response = llm.invoke(prompt)

    try:
        score = float(response.content)
    except ValueError:
        score = 0.0

    return {"doa": score}

def language_node(state: ExamState):
  content_to_analyze = state.get("content", "")
  prompt = f"""
    Analyze this essay for language quality:

    {content_to_analyze}

    Give a language score out of 5.

    IMPORTANT:
    Return ONLY the numerical score.
    Do not give explanation.
    Do not use markdown.
    Do not write anything except the number.

    Example:
    4.2
    """

  language_score_response = llm.invoke(prompt)

  try:
      state["language"] = float(language_score_response.content)
  except ValueError:
      print(f"Warning: Could not convert Language score to float: {language_score_response.content}")
      state["language"] = 0.0 # Default or error value

  return {"language": float(language_score_response.content)}

graph_builder = StateGraph(ExamState)

graph_builder.add_node("generate_title", generate_title_node)
graph_builder.add_node("ask_essay", ask_essay_node)
graph_builder.add_node("cot", cot_node)
graph_builder.add_node("doa", doa_node)
graph_builder.add_node("language", language_node)

graph_builder.add_edge(START, "generate_title")

graph_builder.add_edge(
    "generate_title",
    "ask_essay"
)

graph_builder.add_edge(
    "ask_essay",
    "cot"
)

graph_builder.add_edge(
    "cot",
    "doa"
)

graph_builder.add_edge(
    "doa",
    "language"
)

graph_builder.add_edge(
    "language",
    END
)

from langgraph.checkpoint.memory import MemorySaver
memory = MemorySaver()

graph = graph_builder.compile(
    checkpointer=memory
)

config = {
    "configurable": {
        "thread_id": "css-essay-1"
    }
}

result = graph.invoke(
    {
        "title": "",
        "content": "",
        "cot": 0.0,
        "doa": 0.0,
        "language": 0.0
    },
    config
)

print(result)

user_essay = input("Write your essay: ")

result = graph.invoke(
    Command(resume=user_essay),
    config
)

print(result)

